### ISSUE TITLE
cuda OOM 

### ISSUE THREAD

**Issue by mawenjie1111** [jkulhanek/wild-gaussians#3]
i use our dataset to train ,but  it doesn't work ,  CUDA OOM  so  What type of graphics card did you use during training？
![image](https://github.com/user-attachments/assets/ec95f63b-5796-4223-a49f-ff9fa05ad1da)

**Comment by jkulhanek** [comment]
Hi, I used A100. In your case the problem is perhaps with the data? It tries to allocate 90gb at some point. How many 3d points do you initialise this with?

**Comment by mawenjie1111** [comment]
in my data ，use 11 images  and ply have 30000 point

**Comment by jkulhanek** [comment]
Where does oom occur?

**Comment by mawenjie1111** [comment]
![image](https://github.com/user-attachments/assets/868deb98-d7f0-4433-9d4a-c731635ffaf6)
 this is detailed error report

**Comment by mawenjie1111** [comment]
![image](https://github.com/user-attachments/assets/e6ed0e1d-c62d-416e-a280-06c51f95a926)
 
﻿Other information
﻿

**Comment by jkulhanek** [comment]
I see, your images are too large for dino. You have to use lower res.

**Comment by mawenjie1111** [comment]
> I see, your images are too large for dino. You have to use lower res.

1.6k  or lower？

**Comment by jkulhanek** [comment]
Not sure. Have you tried 1.6k?

**Comment by jkulhanek** [comment]
@mawenjie1111 , is the issue resolved now?

**Comment by mawenjie1111** [comment]
> @mawenjie1111 , is the issue resolved now?

yes. We have solved this problem. Due to being busy, I missed your reply. Thank you for your help
